name: MyPet
main: de.Keyle.MyPet.MyPetPlugin
version: ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}
author: Keyle
website: ${project.url}
softdepend:
  - Ancient
  - BattleArena
  - Citizens
  - Factions
  - GriefPrevention
  - GriefPreventionPlus
  - Heroes
  - Kingdoms
  - MagicSpells
  - mcMMO
  - Minigames
  - MobArena
  - Multiverse-Core
  - NoCheatPlus
  - PlayeholderAPI
  - PlotSquared
  - ProtocolLib
  - pvparena
  - PvPDiffTimer
  - PvPManager
  - Residence
  - ResourcePackApi
  - SkillAPI
  - SurvivalGames
  - Towny
  - Vault
  - WGCustomFlags
  - WorldGuard
commands:
  myPet:
    description: Help for all MyPet commands.
  petname:
    description: Changes the name of your MyPet
    usage: '/<command> <pet name>'
  petcall:
    aliases: [petc, pc]
    description: Calls your MyPet.
  petsendaway:
    aliases: [petsa, psa]
    description: Send your MyPet away.
  petrelease:
    description: Releases your MyPet.
    usage: '/<command> <pet name>'
  petstop:
    aliases: [pets, ps]
    description: Stops your MyPet from attacking.
  petpickup:
    aliases: [petp, pp]
    description: Toogles pickup of your MyPet.
  petinventory:
    aliases: [peti, pi]
    description: Opens the inventory of your MyPet.
    usage: '/<command> [player name]'
  petbehavior:
    aliases: [petb, pb]
    description: Changes the behavior mode of your MyPet.
    usage: '/<command> [<friendly/aggressive/normal/farm/raid/duel>]'
  petinfo:
    aliases: [pinfo]
    description: Shows info about your MyPet
    usage: '/<command> [player name]'
  petskill:
    aliases: [pskill]
    description: Shows the Skill-levels of your MyPet
    usage: '/<command> <player name>'
  mypetadmin:
    aliases: [petadmin]
    description: §6MyPet-Admin-Command §r-> §3https://wiki.mypet-plugin.de/doku.php?id=en:commands
    permission: MyPet.admin
  petskilltree:
    aliases: [pst, petst]
    description: Shows a fully configured skilltree
    usage: '/<command> <mobtype> [skilltree name]'
  petchooseskilltree:
    aliases: [pcst, petcst]
    description: Chooses a skilltree.
    usage: '/<command> <skilltree name>'
  petbeacon:
    aliases: [pbeacon]
    description: Beacon!
  petrespawn:
    aliases: [pr, petr]
    description: Pays respawn fee or enable auto respawn fee paying.
    usage: '/<command> [pay/auto] [min respawn time]'
  pettype:
    description: Shows info about the MyPet-types.
    usage: '/<command> <pet type>'
  petcapturehelper:
    aliases: [pch]
    description: Toogles CaptureHelper on/off
  petoptions:
    aliases: [po, peto, petoption]
    description: MyPet player options
  petswitch:
    aliases: [pswitch, psw]
    description: Opens a MyPet selection GUI
  petlist:
    aliases: [plist, pl]
    description: Lists all your MyPets
    usage: '/<command> <player name>'
  pettrade:
    aliases: [pett, pt]
    description: Trade MyPets with other players
    usage: '/<command> [accept/reject/cancel/<playername>] <price>'
  petshop:
    aliases: [petsh, psh]
    description: Opens a pet shop
    usage: '/<command> [shopname]'

permissions:
  MyPet.leash.*:
    description: Player can leash all MyPet-Types.
    children:
      MyPet.leash.Bat: true
      MyPet.leash.Blaze: true
      MyPet.leash.CaveSpider: true
      MyPet.leash.Chicken: true
      MyPet.leash.Cow: true
      MyPet.leash.Creeper: true
      MyPet.leash.Enderdragon: true
      MyPet.leash.Enderman: true
      MyPet.leash.Endermite: true
      MyPet.leash.Giant: true
      MyPet.leash.Ghast: true
      MyPet.leash.Guardian: true
      MyPet.leash.Horse: true
      MyPet.leash.IronGolem: true
      MyPet.leash.MagmaCube: true
      MyPet.leash.Mooshroom: true
      MyPet.leash.Ocelot: true
      MyPet.leash.Pig: true
      MyPet.leash.PigZombie: true
      MyPet.leash.PolarBear: true
      MyPet.leash.Rabbit: true
      MyPet.leash.Sheep: true
      MyPet.leash.Silverfish: true
      MyPet.leash.Skeleton: true
      MyPet.leash.Slime: true
      MyPet.leash.Snowman: true
      MyPet.leash.Spider: true
      MyPet.leash.Squid: true
      MyPet.leash.Villager: true
      MyPet.leash.Witch: true
      MyPet.leash.Wither: true
      MyPet.leash.Wolf: true
      MyPet.leash.Zombie: true
  MyPet.command.trade.offer.type.*:
    description: Player offer all MyPet-Types.
    children:
      MyPet.command.trade.offer.type.Bat: true
      MyPet.command.trade.offer.type.Blaze: true
      MyPet.command.trade.offer.type.CaveSpider: true
      MyPet.command.trade.offer.type.Chicken: true
      MyPet.command.trade.offer.type.Cow: true
      MyPet.command.trade.offer.type.Creeper: true
      MyPet.command.trade.offer.type.Enderdragon: true
      MyPet.command.trade.offer.type.Enderman: true
      MyPet.command.trade.offer.type.Endermite: true
      MyPet.command.trade.offer.type.Giant: true
      MyPet.command.trade.offer.type.Ghast: true
      MyPet.command.trade.offer.type.Guardian: true
      MyPet.command.trade.offer.type.Horse: true
      MyPet.command.trade.offer.type.IronGolem: true
      MyPet.command.trade.offer.type.MagmaCube: true
      MyPet.command.trade.offer.type.Mooshroom: true
      MyPet.command.trade.offer.type.Ocelot: true
      MyPet.command.trade.offer.type.Pig: true
      MyPet.command.trade.offer.type.PigZombie: true
      MyPet.command.trade.offer.type.PolarBear: true
      MyPet.command.trade.offer.type.Rabbit: true
      MyPet.command.trade.offer.type.Sheep: true
      MyPet.command.trade.offer.type.Silverfish: true
      MyPet.command.trade.offer.type.Skeleton: true
      MyPet.command.trade.offer.type.Slime: true
      MyPet.command.trade.offer.type.Snowman: true
      MyPet.command.trade.offer.type.Spider: true
      MyPet.command.trade.offer.type.Squid: true
      MyPet.command.trade.offer.type.Villager: true
      MyPet.command.trade.offer.type.Witch: true
      MyPet.command.trade.offer.type.Wither: true
      MyPet.command.trade.offer.type.Wolf: true
      MyPet.command.trade.offer.type.Zombie: true
  MyPet.command.trade.receive.type.*:
    description: Player receive all MyPet-Types.
    children:
      MyPet.command.trade.receive.type.Bat: true
      MyPet.command.trade.receive.type.Blaze: true
      MyPet.command.trade.receive.type.CaveSpider: true
      MyPet.command.trade.receive.type.Chicken: true
      MyPet.command.trade.receive.type.Cow: true
      MyPet.command.trade.receive.type.Creeper: true
      MyPet.command.trade.receive.type.Enderdragon: true
      MyPet.command.trade.receive.type.Enderman: true
      MyPet.command.trade.receive.type.Endermite: true
      MyPet.command.trade.receive.type.Giant: true
      MyPet.command.trade.receive.type.Ghast: true
      MyPet.command.trade.receive.type.Guardian: true
      MyPet.command.trade.receive.type.Horse: true
      MyPet.command.trade.receive.type.IronGolem: true
      MyPet.command.trade.receive.type.MagmaCube: true
      MyPet.command.trade.receive.type.Mooshroom: true
      MyPet.command.trade.receive.type.Ocelot: true
      MyPet.command.trade.receive.type.Pig: true
      MyPet.command.trade.receive.type.PigZombie: true
      MyPet.command.trade.receive.type.PolarBear: true
      MyPet.command.trade.receive.type.Rabbit: true
      MyPet.command.trade.receive.type.Sheep: true
      MyPet.command.trade.receive.type.Silverfish: true
      MyPet.command.trade.receive.type.Skeleton: true
      MyPet.command.trade.receive.type.Slime: true
      MyPet.command.trade.receive.type.Snowman: true
      MyPet.command.trade.receive.type.Spider: true
      MyPet.command.trade.receive.type.Squid: true
      MyPet.command.trade.receive.type.Villager: true
      MyPet.command.trade.receive.type.Witch: true
      MyPet.command.trade.receive.type.Wither: true
      MyPet.command.trade.receive.type.Wolf: true
      MyPet.command.trade.receive.type.Zombie: true
  MyPet.admin:
    description: Gives access to the MyPet admin features.
  MyPet.*:
    description: Gives access to MyPet features for normal user.
    children:
      MyPet.leash.*: true
      MyPet.command.respawn: true
      MyPet.command.release: true
      MyPet.command.capturehelper: true
      MyPet.command.name: true
      MyPet.command.name.color: true
      MyPet.command.options: true
      MyPet.command.trade.offer: true
      MyPet.command.trade.offer.type.*: true
      MyPet.command.trade.receive: true
      MyPet.command.trade.receive.type.*: true
      MyPet.command.list: true
  MyPet.command.release:
    description: Allows usage of /petrelease
  MyPet.command.capturehelper:
    description: Gives access to the CaptureHelper
  MyPet.command.respawn:
    description: Allows usage of /petrespawn
  MyPet.command.name:
    description: Allows usage of /petname
  MyPet.command.name.color:
    description: Allows to use colors in petnames
  MyPet.command.options:
    description: Allows to use the MyPet options command
  MyPet.command.switch:
    description: Allows to switch between MyPets
  MyPet.command.info.other:
    description: Allows to view info about pets from other players with "/petinfo <playername>"
  MyPet.extended.feed:
    description: Extended permission. Allows to feed pets.
  MyPet.extended.equip:
    description: Extended permission. Allows to equip pets.
  MyPet.extended.beacon:
    description: Extended permission. Allows to open the beacon GUI.
  MyPet.extended.inventory:
    description: Extended permission. Allows to open the inventory of the pet.
  MyPet.extended.ride:
    description: Extended permission. Allows to mount pets.
  MyPet.extended.control:
    description: Extended permission. Allows to control pets.
  MyPet.extended.pickup:
    description: Extended permission. Allows to enable pickup.
  MyPet.extended.behavior.friendly:
    description: Extended permission. Allows to use the ´friendly´ behavior.
  MyPet.extended.behavior.aggressive:
    description: Extended permission. Allows to use the ´aggressive´ behavior.
  MyPet.extended.behavior.farm:
    description: Extended permission. Allows to use the ´farm´ behavior.
  MyPet.extended.behavior.raid:
    description: Extended permission. Allows to use the ´raid´ behavior.
  MyPet.extended.behavior.duel:
    description: Extended permission. Allows to use the ´duel´ behavior.