name: MyPet
main: de.Keyle.MyPet.MyPetPlugin
version: ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}
api-version: 1.13
author: Keyle
website: ${project.url}
softdepend:
  - Ancient
  - BattleArena
  - Citizens
  - Factions
  - GangsPlus
  - GriefPrevention
  - GriefPreventionPlus
  - Heroes
  - Kingdoms
  - MagicSpells
  - mcMMO
  - MiniaturePets
  - Minigames
  - MobArena
  - Multiverse-Core
  - MythicMobs
  - NoCheatPlus
  - PlaceholderAPI
  - PlotSquared
  - PreciousStones
  - PremiumVanish
  - ProtocolLib
  - pvparena
  - PvPDiffTimer
  - PvPManager
  - RedProtect
  - Residence
  - SimpleClans
  - SkillAPI
  - SuperVanish
  - SurvivalGames
  - Towny
  - Vault
  - WGCustomFlags
  - WorldGuard
commands:
  myPet:
    description: Help for all pet commands.
  petname:
    description: Changes the name of your pet
    usage: '/<command> <pet name>'
  petcall:
    aliases: [petc, pc]
    description: Calls your pet.
  petsendaway:
    aliases: [petsa, psa]
    description: Send your pet away.
  petrelease:
    description: Releases your pet.
    usage: '/<command> <pet name>'
  petstop:
    aliases: [pets, ps]
    description: Stops your pet from attacking.
  petpickup:
    aliases: [petp, pp]
    description: Toogles pickup of your pet.
  petinventory:
    aliases: [peti, pi]
    description: Opens the inventory of your pet.
    usage: '/<command> [player name]'
  petbehavior:
    aliases: [petbehaviour, petb, pb]
    description: Changes the behavior mode of your pet.
    usage: '/<command> [<friendly/aggressive/normal/farm/raid/duel>]'
  petinfo:
    aliases: [pinfo]
    description: Shows info about your pet.
    usage: '/<command> [player name]'
  petskill:
    aliases: [pskill]
    description: Shows the skill levels of your pet.
    usage: '/<command> <player name>'
  mypetadmin:
    aliases: [petadmin]
    description: §6MyPet-Admin-Command §r-> §3https://wiki.mypet-plugin.de/doku.php?id=en:commands
    permission: MyPet.admin
  petchooseskilltree:
    aliases: [pcst, petcst]
    description: Chooses a skilltree.
    usage: '/<command> <skilltree name>'
  petbeacon:
    aliases: [pbeacon]
    description: Beacon!
  petrespawn:
    aliases: [pr, petr]
    description: Pays respawn fee or enable auto respawn fee paying.
    usage: '/<command> [pay/auto] [min respawn time]'
  petsettings:
    aliases: [po, peto, petoption, petoptions, psettings]
    description: Settings command
  petswitch:
    aliases: [pswitch, psw]
    description: Opens a pet selection GUI
  petstore:
    aliases: [pstore, pst]
    description: Stores your current pet
  petlist:
    aliases: [plist, pl]
    description: Lists all your pet
    usage: '/<command> <player name>'

permissions:
  MyPet.leash.*:
    description: Player can leash all MyPet-Types.
    children:
      MyPet.leash.Bat: true
      MyPet.leash.Blaze: true
      MyPet.leash.CaveSpider: true
      MyPet.leash.Chicken: true
      MyPet.leash.Cod: true
      MyPet.leash.Cow: true
      MyPet.leash.Creeper: true
      MyPet.leash.Dolphin: true
      MyPet.leash.Donkey: true
      MyPet.leash.Drowned: true
      MyPet.leash.ElderGuardian: true
      MyPet.leash.Enderdragon: true
      MyPet.leash.Enderman: true
      MyPet.leash.Endermite: true
      MyPet.leash.Evoker: true
      MyPet.leash.Giant: true
      MyPet.leash.Ghast: true
      MyPet.leash.Guardian: true
      MyPet.leash.Horse: true
      MyPet.leash.Husk: true
      MyPet.leash.Illusioner: true
      MyPet.leash.IronGolem: true
      MyPet.leash.Llama: true
      MyPet.leash.MagmaCube: true
      MyPet.leash.Mooshroom: true
      MyPet.leash.Mule: true
      MyPet.leash.Ocelot: true
      MyPet.leash.Parrot: true
      MyPet.leash.Phantom: true
      MyPet.leash.Pig: true
      MyPet.leash.PigZombie: true
      MyPet.leash.PolarBear: true
      MyPet.leash.Pufferfish: true
      MyPet.leash.Rabbit: true
      MyPet.leash.Salmon: true
      MyPet.leash.Sheep: true
      MyPet.leash.Silverfish: true
      MyPet.leash.Skeleton: true
      MyPet.leash.SkeletonHorse: true
      MyPet.leash.Slime: true
      MyPet.leash.Snowman: true
      MyPet.leash.Spider: true
      MyPet.leash.Squid: true
      MyPet.leash.Stray: true
      MyPet.leash.TropicalFish: true
      MyPet.leash.Turtle: true
      MyPet.leash.Vex: true
      MyPet.leash.Villager: true
      MyPet.leash.Vindicator: true
      MyPet.leash.Witch: true
      MyPet.leash.Wither: true
      MyPet.leash.WitherSkeleton: true
      MyPet.leash.Wolf: true
      MyPet.leash.Zombie: true
      MyPet.leash.ZombieHorse: true
      MyPet.leash.ZombieVillager: true
  MyPet.admin:
    description: Gives access to the MyPet admin features.
  MyPet.*:
    description: Gives access to MyPet features for normal user.
    children:
      MyPet.leash.*: true
      MyPet.command.respawn: true
      MyPet.command.release: true
      MyPet.command.name: true
      MyPet.command.name.color: true
      MyPet.command.options: true
      MyPet.command.list: true
  MyPet.command.release:
    description: Allows usage of /petrelease
  MyPet.command.respawn:
    description: Allows usage of /petrespawn
  MyPet.command.name:
    description: Allows usage of /petname
  MyPet.command.name.color:
    description: Allows to use colors in petnames
  MyPet.command.options:
    description: Allows to use the MyPet options command
  MyPet.command.switch:
    description: Allows to switch between MyPets
  MyPet.command.info.other:
    description: Allows to view info about pets from other players with "/petinfo <playername>"
  MyPet.extended.feed:
    description: Extended permission. Allows to feed pets.
  MyPet.extended.equip:
    description: Extended permission. Allows to equip pets.
  MyPet.extended.beacon:
    description: Extended permission. Allows to open the beacon GUI.
  MyPet.extended.inventory:
    description: Extended permission. Allows to open the inventory of the pet.
  MyPet.extended.ride:
    description: Extended permission. Allows to mount pets.
  MyPet.extended.control:
    description: Extended permission. Allows to control pets.
  MyPet.extended.pickup:
    description: Extended permission. Allows to enable pickup.
  MyPet.extended.behavior.friendly:
    description: Extended permission. Allows to use the ´friendly´ behavior.
  MyPet.extended.behavior.aggressive:
    description: Extended permission. Allows to use the ´aggressive´ behavior.
  MyPet.extended.behavior.farm:
    description: Extended permission. Allows to use the ´farm´ behavior.
  MyPet.extended.behavior.raid:
    description: Extended permission. Allows to use the ´raid´ behavior.
  MyPet.extended.behavior.duel:
    description: Extended permission. Allows to use the ´duel´ behavior.
  MyPet.experience.multiplier.125:
    description: Grants 25% extra experience.
  MyPet.experience.multiplier.150:
    description: Grants 50% extra experience.
  MyPet.experience.multiplier.175:
    description: Grants 75% extra experience.
  MyPet.experience.multiplier.200:
    description: Grants 100% extra experience.
  MyPet.experience.multiplier.225:
    description: Grants 125% extra experience.
  MyPet.experience.multiplier.250:
    description: Grants 150% extra experience.