# the order of this skilltrees is from top (admins eg.) to the bottom (losers)

skilltrees:

  # Admin skilltree -> MyPet.custom.skilltree.admin
  admin:
    '1':
      - Inventory
      - Inventory
      - Inventory
      - Inventory
      - Inventory
      - Inventory
      - Control
      - Pickup
      - Behavior
      - HP
      - HP
      - HP
      - HP
      - HP

  # Hunter skilltree -> MyPet.custom.skilltree.Hunter
  Hunter:
    inherit: Pickup
    '2':
      - Control
      - Inventory
      - Damage
      - Damage
      - Poison
    '4':
      - HP
      - Damage
    '6':
      - Inventory
      - Behavior
      - Poison
    '8':
      - Inventory
      - HP
      - Damage
    '10':
      - Inventory
      - HP
      - Damage
      - Poison
    '12':
      - Inventory
      - HP
      - Damage
    '14':
      - Inventory
      - HP
      - Damage
    '16':
      - HP
      - Damage
    '18':
      - HP
      - Damage
    '20':
      - HP
      - Damage

  # every normal should have permissions for this skilltree -> MyPet.custom.skilltree.default
  default:
    '2':
      - Inventory
    '4':
      - Inventory
      - Control
      - HP
      - Damage
      - Poison
    '6':
      - Inventory
      - Behavior
      - Poison
    '8':
      - Pickup
      - HP
      - Damage
    '10':
      - Inventory
      - HP
      - Damage
      - Poison
    '12':
      - Inventory
      - HP
      - Damage
    '14':
      - Inventory
      - HP
      - Damage
    '16':
      - HP
      - Damage
    '18':
      - HP
      - Damage
    '20':
      - HP
      - Damage

  # skilltree for loser :P every MyPet with this skilltree will have NO skills -> MyPet.custom.skilltree.loser
  loser:
    '1':

# -------------------------------------------------------------------------------------------------------------------------------------

  # Hunter will inherit this
  Pickup:
    '2':
      - Pickup
