name: MyWolf
main: de.Keyle.MyWolf.MyWolfPlugin
version: 0.5.5
author: Keyle
website: http://dev.bukkit.org/server-mods/mywolf/
softdepend: [GroupManager, Permissions, PermissionsEX, WorldGuard]
commands:
  wolf:
    description: wolf commands
  wolfname:
    description: set the name of the wolf
    usage: 'Syntax: /<command> <WolfName>'
  wolfcall:
    aliases: [wc,wolfc]
    description: call your wolf
  wolfrelease:
    description: release your wolf
    usage: 'Syntax: /<command> <WolfName>'
  wolfstop:
    aliases: [ws,wolfs]
    description: you wolf stopping attacking
  wolfpickup:
    aliases: [wp,wolfp]
    description: toogle pickup
  wolfinventory:
    aliases: [wi,wolfi]
    description: open inventory of the wolf
  wolfbehavior:
    aliases: [wb,wolfb]
    description: switch the behavior mode
    usage: 'Syntax: /<command> [<Raid/Friendly/Aggressive/Normal>]'
  wolfinfo:
    aliases: [winfo]
    description: display HP and EXP of your MyWolf
    usage: 'Syntax: /<command> [PlayerName]'