name: MyWolf
main: de.Keyle.MyWolf.MyWolf
version: 0.4.2
author: Keyle
website: http://forums.bukkit.org/threads/16014/
commands:
  wolf:
    description: wolf commands
  wolfname:
    description: set the name of the wolf
  wolfcall:
    aliases: [wc,wolfc]
    description: call your wolf
  wolfrelease:
    description: release your wolf
  wolfstop:
    aliases: [ws,wolfs]
    description: you wolf stopping attacking
