name: MyWolf
main: de.Keyle.MyWolf.MyWolfPlugin
version: 0.5.0
author: Keyle
website: http://forums.bukkit.org/threads/16014/
softdepend: [GroupManager, Permissions, PermissionsEX, WorldGuard]
depend: [Spout]
commands:
  wolf:
    description: wolf commands
  wolfname:
    description: set the name of the wolf
    usage: 'Syntax: /<command> <WolfName>'
  wolfcall:
    aliases: [wc,wolfc]
    description: call your wolf
  wolfrelease:
    description: release your wolf
    usage: 'Syntax: /<command> <WolfName>'
  wolfstop:
    aliases: [ws,wolfs]
    description: you wolf stopping attacking
  wolfpickup:
    aliases: [wp,wolfp]
    description: toogle pickup
  wolfinventory:
    aliases: [wi,wolfi]
    description: open inventory of the wolf
  wolfbehavior:
    aliases: [wb,wolfb]
    description: switch the behavior mode
    usage: 'Syntax: /<command> [<Raid/Friendly/Aggressive/Normal>]'
  wolfexp:
    aliases: [we,wolfe]
    description: display wolf's EXP
  wolfinfo:
    aliases: [winfo]
    description: display wolf's HP and EXP
  wolfcompass:
    aliases: [wcomp,wolfcomp]
    description: Let the compass points to your wolf
  wolfskin:
    description: Set the skin of a wolf