name: MyWolf
main: de.Keyle.MyWolf.MyWolf
version: 0.4.6
author: Keyle
website: http://forums.bukkit.org/threads/16014/
softdepend: [GroupManager, Permissions, BukkitContrib]
commands:
  wolf:
    description: wolf commands
  wolfname:
    description: set the name of the wolf
    usage: 'Syntax: /<command> <WolfName>'
  wolfcall:
    aliases: [wc,wolfc]
    description: call your wolf
  wolfrelease:
    description: release your wolf
    usage: 'Syntax: /<command> <WolfName>'
  wolfstop:
    aliases: [ws,wolfs]
    description: you wolf stopping attacking