name: MyWolf
main: de.Keyle.MyWolf.MyWolfPlugin
version: 0.6.2
author: Keyle
website: http://dev.bukkit.org/server-mods/mywolf/
softdepend: [Vault, Citizens, WorldGuard]
commands:
  mywolf:
    description: Help for all MyWolf commands.
  wolfname:
    description: Set the name of your MyWolf
    usage: '/<command> <WolfName>'
  wolfcall:
    aliases: [wolfc, wc]
    description: Call your MyWolf.
  wolfrelease:
    description: Release your MyWolf.
    usage: '/<command> <WolfName>'
#  wolfstop:
#    aliases: [wolfs, ws]
#    description: your MyWolf stop attacking.
  wolfpickup:
    aliases: [wolfp, wp]
    description: Toogles pickup of your MyWolf.
  wolfinventory:
    aliases: [wolfi, wi]
    description: Open the inventory of your MyWolf.
#  wolfbehavior:
#    aliases: [wolfb, wb]
#    description: Switch the behavior mode of your MyWolf.
#    usage: '/<command> [<Raid/rai/Friendly/fri/Aggressive/agg/Normal/nor>]'
  wolfinfo:
    aliases: [winfo]
    description: Shows HP and Exp of your MyWolf
    usage: '/<command> [PlayerName]'
  wolfskill:
    aliases: [wskill]
    description: Shows the skill-levels of a online MyWolf
    usage: '/<command> <playername>'
  wolfadmin:
    aliases: [wolfa, wa]
    description: Set the Exp or Name of a MyWolf
    usage: '/<command> [PlayerName] name/exp [Value]'

permissions:
  MyWolf.*:
    description: Gives access to ALL Mywolf commands
    children:
      MyWolf.admin: true
      MyWolf.user.leash: true
#      MyWolf.user.stop: true
      MyWolf.user.call: true
      MyWolf.user.setname: true
      MyWolf.user.release: true
  MyWolf.user.*:
    description: Gives access to MyWolf user commands
    children:
      MyWolf.admin: false
      MyWolf.user.leash: true
#      MyWolf.user.stop: true
      MyWolf.user.call: true
      MyWolf.user.setname: true
      MyWolf.user.release: true
  MyWolf.user.leash:
    description: Allows a player to leash a MyWolf.
#  MyWolf.user.stop:
#    description: Allows useage of /wolfstop
  MyWolf.user.call:
    description: Allows useage of /wolfcall
  MyWolf.user.setname:
    description: Allows useage of /wolfname
  MyWolf.user.release:
    description: Allows useage of /wolfrelease
  MyWolf.admin:
    description: Allows user to use some MyWolf-admin functions.